export const GDS_API = process.env.GDS_API || 'http://localhost:8080/gds';
export const FILE_SERVICE = GDS_API + '/fileServicePort';
export const UPLOAD_SINGLE_FILE = FILE_SERVICE + '/uploadSingleFile';
export const UPLOAD_BASE_URL = UPLOAD_SINGLE_FILE + '?multipart=true&multipartField=uploadFile';
export const READ_FILE = FILE_SERVICE + '/readFile?isFile=true&param=fileId:';
export const FILE_DOMAIN = process.env.FILE_DOMAIN || 'Files';
export const CATEGORY_DOMAIN = process.env.CATEGORY_DOMAIN || 'Category';
export const ITEM_DOMAIN = process.env.ITEM_DOMAIN || 'Items';
export const CATALOGING_DOMAIN = process.env.CATALOGING_DOMAIN || 'Cataloguing';
export const CATALOGING_DOMAIN_SEARCH_ONLINE = 'searchOnline';
export const CATALOGING_DOMAIN_IMPORT_MARC_DATA = 'importMarcData';
export const CATALOGING_DOMAIN_GET_ITEMS = 'getItems';